import subprocess, time, ast

fp = "backend/app/api/v1/endpoints/agents_api.py"
with open(fp, "r", encoding="utf-8-sig") as f:
    code = f.read()

ENGINE = r'''
var API="/api/v1/dashboard";
var TOKEN=localStorage.getItem("sodangi_token")||"";
var ROLE=localStorage.getItem("sodangi_role")||"";
var NAME=localStorage.getItem("sodangi_name")||"";
window.SHOWROOM_URL="";
function toast(m,c){var t=document.getElementById("toast");if(!t)return;t.textContent=m;t.style.background=c||"#16A34A";t.style.display="block";setTimeout(function(){t.style.display="none";},3000);}
window.addEventListener("error",function(ev){try{toast("Error: "+(ev.message||"unknown"),"#EF4444");}catch(e){}});
async function api(p,m,b,a,attempt){attempt=attempt||0;var ctrl=new AbortController();var timer=setTimeout(function(){ctrl.abort();},20000);var h={"Content-Type":"application/json"};if(a)h["Authorization"]="Bearer "+TOKEN;try{var r=await fetch(API+p,{method:m,headers:h,body:b?JSON.stringify(b):undefined,signal:ctrl.signal});clearTimeout(timer);if(!r.ok){var e={};try{e=await r.json();}catch(x){}throw new Error(e.detail||("HTTP "+r.status));}return await r.json();}catch(err){clearTimeout(timer);var msg=err.message||"";var net=(err.name==="AbortError")||msg.indexOf("Failed to fetch")>-1;if(net&&attempt<2){await new Promise(function(res){setTimeout(res,1200*(attempt+1));});return api(p,m,b,a,attempt+1);}throw new Error(net?"Network slow or offline. Please retry.":err.message);}}
function go(tab){["Upload","Cars","Agents","Stats","Profile","Leads","Leaderboard","SMS","Bot"].forEach(function(t){var el=document.getElementById("tab"+t);if(el)el.classList.add("hidden");var nb=document.getElementById("nav"+t);if(nb)nb.classList.remove("active");});var el=document.getElementById("tab"+tab);if(el)el.classList.remove("hidden");var nb=document.getElementById("nav"+tab);if(nb)nb.classList.add("active");if(tab==="Cars")loadCars();if(tab==="Agents")loadAgents();if(tab==="Profile")loadProfile();if(tab==="Stats")loadStats();if(tab==="Leads")loadLeads();if(tab==="Leaderboard")loadLeaderboard();if(tab==="Bot")loadBot();}
function enterDash(){var ac=document.getElementById("authCard");if(ac)ac.classList.add("hidden");var ph=document.getElementById("publicHome");if(ph)ph.style.display="none";var mh=document.getElementById("mainHeader");if(mh)mh.classList.remove("hidden");var bn=document.getElementById("bottomNav");if(bn)bn.classList.remove("hidden");var who=document.getElementById("who");if(who)who.textContent=NAME+" ("+ROLE+")";if(ROLE==="owner"){var na=document.getElementById("navAgents");if(na)na.classList.remove("hidden");var ns=document.getElementById("navStats");if(ns)ns.classList.remove("hidden");}go("Upload");}
function showAuth(mode){var lp=document.getElementById("loginPane");var sp=document.getElementById("signupPane");var lb=document.getElementById("tabLoginBtn");var sb=document.getElementById("tabSignupBtn");if(!lp||!sp)return;if(mode==="login"){lp.classList.remove("hidden");sp.classList.add("hidden");if(lb)lb.className="btn btn-primary";if(sb)sb.className="btn btn-ghost";}else{sp.classList.remove("hidden");lp.classList.add("hidden");if(sb)sb.className="btn btn-primary";if(lb)lb.className="btn btn-ghost";}if(lb)lb.style.margin="0";if(sb)sb.style.margin="0";}
async function doLogin(){var email=document.getElementById("liEmail").value.trim();var pass=document.getElementById("liPass").value;if(!email||!pass){alert("Please fill Email and Password");return;}try{var r=await fetch(API+"/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:email,password:pass})});var data=await r.json();if(data.status==="wrong_password"){alert("Wrong password!\nOwner: Sodangi2026!");return;}if(!data.token){alert("Server error: "+JSON.stringify(data));return;}TOKEN=data.token;ROLE=data.role;NAME=data.full_name;localStorage.setItem("sodangi_token",TOKEN);localStorage.setItem("sodangi_role",ROLE);localStorage.setItem("sodangi_name",NAME);enterDash();}catch(e){alert("Network error: "+e.message);}}
async function registerAgent(){var n=document.getElementById("regName").value.trim();var e=document.getElementById("regEmail").value.trim();var p=document.getElementById("regPass").value;if(!n||!e||!p){alert("Fill all registration fields");return;}try{var r=await fetch(API+"/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({full_name:n,email:e,password:p})});var d=await r.json();if(r.ok){alert("Account created! Role: "+(d.role||"agent")+"\nNow tap Sign In.");showAuth("login");}else{alert("Registration failed: "+(d.detail||"unknown"));}}catch(err){alert("Registration failed: "+err.message);}}
async function initSocial(){try{var r=await fetch(API+"/social-config");var c=await r.json();if(c.google_client_id){var s=document.createElement("script");s.src="https://accounts.google.com/gsi/client";s.async=true;s.onload=function(){try{google.accounts.id.initialize({client_id:c.google_client_id,callback:onGoogleCred});google.accounts.id.renderButton(document.getElementById("googleBtn"),{theme:"filled_black",size:"large",width:300,text:"signup_with"});}catch(e){}};document.head.appendChild(s);}else{var w=document.getElementById("googleBtnWrap");if(w)w.style.display="none";var dv=document.getElementById("authDivider");if(dv)dv.style.display="none";}}catch(e){var w2=document.getElementById("googleBtnWrap");if(w2)w2.style.display="none";}}
async function onGoogleCred(resp){try{var r=await fetch(API+"/social-login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({credential:resp.credential})});var d=await r.json();if(d.token){TOKEN=d.token;ROLE=d.role;NAME=d.full_name;localStorage.setItem("sodangi_token",TOKEN);localStorage.setItem("sodangi_role",ROLE);localStorage.setItem("sodangi_name",NAME);enterDash();}else{alert("Google sign-in failed: "+(d.detail||"unknown"));}}catch(e){alert("Google sign-in error: "+e.message);}}
function logout(){localStorage.removeItem("sodangi_token");localStorage.removeItem("sodangi_role");localStorage.removeItem("sodangi_name");location.reload();}
function copyShowroom(){if(window.SHOWROOM_URL){navigator.clipboard.writeText(window.SHOWROOM_URL);toast("Showroom link copied!");}}
function compressImage(file,maxW){return new Promise(function(res,rej){var img=new Image();var url=URL.createObjectURL(file);img.onload=function(){var w=img.width,h=img.height;if(w>maxW){h=Math.round(h*maxW/w);w=maxW;}var c=document.createElement("canvas");c.width=w;c.height=h;var ctx=c.getContext("2d");ctx.drawImage(img,0,0,w,h);URL.revokeObjectURL(url);c.toBlob(function(b){if(b)res(b);else rej(new Error("compress fail"));},"image/jpeg",0.72);};img.onerror=function(){URL.revokeObjectURL(url);rej(new Error("load fail"));};img.src=url;});}
async function uploadMedia(){var files=document.getElementById("pFile").files;if(!files.length)return;var prev=document.getElementById("mediaPreview");var urls=[];for(var i=0;i<files.length;i++){var f=files[i];var oname=f.name;prev.textContent="Compressing "+(i+1)+" of "+files.length+"...";try{f=await compressImage(f,800);var dot=oname.lastIndexOf(".");oname=(dot>0?oname.substring(0,dot):oname)+".jpg";}catch(e){}prev.textContent="Uploading "+(i+1)+" of "+files.length+" ("+Math.round(f.size/1024)+"KB)...";try{var fd=new FormData();fd.append("file",f,oname);var r=await fetch(API+"/upload-media",{method:"POST",headers:{"Authorization":"Bearer "+TOKEN},body:fd});if(!r.ok)throw new Error("relay");var d=await r.json();urls.push(d.url);}catch(e){alert("Upload failed for "+oname);}}document.getElementById("pImg").value=JSON.stringify(urls);prev.textContent="Done! "+urls.length+" photo(s) uploaded.";}
async function uploadProduct(){var nameV=document.getElementById("pName").value;var priceV=parseFloat(document.getElementById("pPrice").value);if(!nameV||isNaN(priceV)){alert("Please fill Name and Price!");return;}var urls=[];try{urls=JSON.parse(document.getElementById("pImg").value||"[]");}catch(e){}if(!urls||urls.length===0){urls=["https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb"];}try{var r=await api("/products/upload","POST",{name:nameV,price:priceV,image_url:JSON.stringify(urls),description:document.getElementById("pDesc").value,stock:1},true);alert("Car published successfully!");document.getElementById("pName").value="";document.getElementById("pPrice").value="";document.getElementById("pDesc").value="";document.getElementById("pFile").value="";document.getElementById("pImg").value="[]";go("Cars");}catch(e){alert("Failed to publish: "+e.message);}}
async function loadCars(){try{var CARS=await api("/products/mine","POST",{},true);var box=document.getElementById("carsList");box.innerHTML="";if(!CARS.length){box.innerHTML="<p style='color:#94A3B8;text-align:center;padding:20px'>No vehicles yet.</p>";return;}window.CARS=CARS;CARS.forEach(function(c,idx){var d=document.createElement("div");d.className="item";d.style.flexDirection="column";var imgs=(c.images&&c.images.length>0)?c.images:[];var h='<div class="item-info"><h3>'+c.name+'</h3><p>&#8358;'+Number(c.price).toLocaleString()+'</p></div>';if(imgs.length>0){h+='<div class="gallery" style="margin:10px 0">';imgs.forEach(function(url){h+='<img src="'+url+'" loading="lazy">';});h+='</div>';}h+='<div style="display:flex;flex-wrap:wrap;gap:6px">';h+='<button class="btn btn-primary" style="flex:1;padding:10px;margin:0;background:#3B82F6;color:#fff;font-size:12px" onclick="openShareModal('+idx+')">Share</button>';h+='<button class="btn btn-primary" style="flex:1;padding:10px;margin:0;background:#25D366;color:#000;font-size:12px" onclick="openBroadcastModal('+idx+')">Broadcast</button>';h+='<button class="btn btn-primary" style="flex:1;padding:10px;margin:0;background:#8B5CF6;color:#fff;font-size:12px" onclick="openSMSModal('+idx+')">SMS</button>';h+='<button class="btn btn-ghost" style="flex:1;padding:10px;margin:0;font-size:12px" onclick="logSale('+idx+')">Log Sale</button>';h+='<button class="btn btn-danger" style="flex:1;padding:10px;margin:0;font-size:12px" onclick="delCar('+c.id+')">Delete</button>';h+='</div>';d.innerHTML=h;box.appendChild(d);});}catch(e){document.getElementById("carsList").innerHTML='<p style="color:#EF4444;text-align:center">'+e.message+'</p>';}}
async function delCar(pid){if(!confirm("Delete?"))return;try{await api("/products/delete","POST",{product_id:pid},true);toast("Deleted");loadCars();}catch(e){alert(e.message);}}
function openShareModal(idx){var car=window.CARS[idx];if(!car)return;var link=location.origin+"/api/v1/dashboard/car/"+car.id;var cap=car.name+" - &#8358;"+Number(car.price).toLocaleString()+" "+link;var h='<div id="shareModal" style="position:fixed;inset:0;background:rgba(0,0,0,0.9);z-index:999;display:flex;align-items:center;justify-content:center;padding:20px"><div style="background:#151F38;border-radius:16px;padding:20px;max-width:400px;width:100%"><h2 style="color:#F8FAFC">'+car.name+'</h2><a href="https://wa.me/?text='+encodeURIComponent(cap)+'" target="_blank" class="btn btn-primary" style="background:#25D366;color:#000">WhatsApp</a><a href="https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(link)+'" target="_blank" class="btn btn-primary" style="background:#1877F2;color:#fff">Facebook</a><button class="btn btn-ghost" onclick="document.getElementById(\'shareModal\').remove()">Close</button></div></div>';document.body.insertAdjacentHTML("beforeend",h);}
function openBroadcastModal(idx){var car=window.CARS[idx];if(!car)return;if(!window._leads||!window._leads.length){alert("Add leads first!");go("Leads");return;}var msg="Check out "+car.name+" for &#8358;"+Number(car.price).toLocaleString()+". "+location.origin+"/api/v1/dashboard/car/"+car.id;var h='<div id="bcModal" style="position:fixed;inset:0;background:rgba(0,0,0,0.9);z-index:999;display:flex;align-items:center;justify-content:center;padding:20px"><div style="background:#151F38;border-radius:16px;padding:20px;max-width:400px;width:100%;max-height:80vh;overflow-y:auto"><h2 style="color:#F8FAFC">Broadcast</h2>';window._leads.forEach(function(l){var p=l.phone.startsWith("234")?l.phone:"234"+l.phone.replace(/^0/,"");h+='<a href="https://wa.me/'+p+'?text='+encodeURIComponent(msg)+'" target="_blank" class="item" style="text-decoration:none;color:#F8FAFC"><h3>'+l.name+'</h3><p>'+l.phone+'</p></a>';});h+='<button class="btn btn-ghost" onclick="document.getElementById(\'bcModal\').remove()">Close</button></div></div>';document.body.insertAdjacentHTML("beforeend",h);}
function openSMSModal(idx){var car=window.CARS[idx];if(!car)return;if(!window._leads||!window._leads.length){alert("Add SMS leads!");go("Leads");return;}var sms=window._leads.filter(function(l){return (l.contact_type||"whatsapp")==="sms";});if(!sms.length){alert("No SMS leads.");go("Leads");return;}var msg="Check out "+car.name+" for &#8358;"+Number(car.price).toLocaleString()+". "+location.origin+"/api/v1/dashboard/car/"+car.id;var h='<div id="smsModal" style="position:fixed;inset:0;background:rgba(0,0,0,0.9);z-index:999;display:flex;align-items:center;justify-content:center;padding:20px"><div style="background:#151F38;border-radius:16px;padding:20px;max-width:400px;width:100%;max-height:80vh;overflow-y:auto"><h2 style="color:#F8FAFC">SMS Blaster</h2>';sms.forEach(function(l){var p=l.phone.startsWith("234")?l.phone:"234"+l.phone.replace(/^0/,"");h+='<a href="sms:+'+p+'?&body='+encodeURIComponent(msg)+'" class="item" style="text-decoration:none;color:#F8FAFC"><h3>'+l.name+'</h3><p>'+l.phone+'</p></a>';});h+='<button class="btn btn-ghost" onclick="document.getElementById(\'smsModal\').remove()">Close</button></div></div>';document.body.insertAdjacentHTML("beforeend",h);}
async function logSale(idx){var car=window.CARS[idx];if(!car)return;if(!confirm("Log sale for "+car.name+"?"))return;try{var me=await api("/profile/me","GET",null,true);var r=await api("/sales/log","POST",{product_id:car.id,agent_id:me.id,sale_price:car.price},true);alert("Sale logged! Commission: &#8358;"+Number(r.commission).toLocaleString());}catch(e){alert(e.message);}}
async function loadLeaderboard(){var box=document.getElementById("leaderboardList");if(!box)return;box.innerHTML="<p style='color:#94A3B8;text-align:center;padding:20px'>Calculating...</p>";try{var b=await api("/leaderboard","GET",null,true);if(!b.length){box.innerHTML="<p style='color:#94A3B8;text-align:center'>No sales yet.</p>";return;}var h='<table style="width:100%;border-collapse:collapse;color:#F8FAFC;font-size:14px"><tr style="border-bottom:1px solid #334155"><th>Agent</th><th>Sales</th><th>Commission</th></tr>';b.forEach(function(a,i){var m=i===0?"&#129351;":i===1?"&#129352;":i===2?"&#129353;":"";h+='<tr style="border-bottom:1px solid #1E293B"><td>'+m+" "+a.name+'</td><td>'+a.sales_count+'</td><td style="color:#10B981;font-weight:bold">&#8358;'+Number(a.commission).toLocaleString()+'</td></tr>';});h+="</table>";box.innerHTML=h;}catch(e){box.innerHTML='<p style="color:#EF4444">'+e.message+'</p>';}}
async function loadLeads(){var box=document.getElementById("leadsList");if(!box)return;try{var leads=await api("/leads/all","GET",null,true);window._leads=leads;if(!leads.length){box.innerHTML="<p style='color:#94A3B8;text-align:center'>No leads saved yet.</p>";return;}var h="";leads.forEach(function(l){var badge=(l.contact_type==="sms")?'<span style="background:#3B82F6;color:#fff;padding:2px 6px;border-radius:4px;font-size:10px">SMS</span>':'<span style="background:#25D366;color:#000;padding:2px 6px;border-radius:4px;font-size:10px">WA</span>';h+='<div class="item"><div class="item-info"><h3>'+l.name+badge+'</h3><p>'+l.phone+'</p></div></div>';});box.innerHTML=h;}catch(e){box.innerHTML='<p style="color:#EF4444">'+e.message+'</p>';}}
async function addLead(){var n=document.getElementById("leadName").value;var p=document.getElementById("leadPhone").value.replace(/\s+/g,"");if(!n||!p){alert("Fill name and phone!");return;}var t=document.getElementById("leadType")?document.getElementById("leadType").value:"whatsapp";try{await api("/leads/add","POST",{name:n,phone:p,contact_type:t},true);alert("Lead saved!");document.getElementById("leadName").value="";document.getElementById("leadPhone").value="";loadLeads();}catch(e){alert(e.message);}}
async function loadAgents(){try{var as=await api("/agents","GET",null,true);var box=document.getElementById("agentsList");if(!box)return;box.innerHTML="";as.forEach(function(a){var d=document.createElement("div");d.className="item";d.innerHTML='<div class="item-info"><h3>'+a.full_name+'</h3><p>'+a.email+'</p></div>';box.appendChild(d);});}catch(e){}}
async function createAgent(){try{var r=await api("/agents/create","POST",{full_name:document.getElementById("aName").value,email:document.getElementById("aEmail").value,password:document.getElementById("aPass").value,phone:document.getElementById("aPhone").value},true);alert("Agent created!");loadAgents();}catch(e){alert(e.message);}}
async function loadProfile(){try{var me=await api("/profile/me","GET",null,true);document.getElementById("mPhone").value=me.phone;document.getElementById("mBio").value=me.bio;var sid=me.page.split("/").pop();window.SHOWROOM_URL=location.origin+"/api/v1/dashboard/ad/"+sid;var sec=document.getElementById("tabProfile");var old=document.getElementById("showroomBox");if(old)old.remove();var d=document.createElement("div");d.id="showroomBox";d.style.marginTop="12px";d.innerHTML='<a href="'+window.SHOWROOM_URL+'" target="_blank" class="btn btn-primary" style="display:block;text-decoration:none;text-align:center">Open My Showroom</a><button class="btn btn-ghost" onclick="copyShowroom()">Copy Showroom Link</button><a class="btn btn-primary" style="display:block;text-decoration:none;text-align:center;background:#25D366;color:#000" href="https://wa.me/?text='+encodeURIComponent("Check out my showroom at Sodangi Motors: "+window.SHOWROOM_URL)+'" target="_blank">Share Showroom on WhatsApp</a>';var btns=sec.querySelectorAll("button");if(btns.length){btns[0].insertAdjacentElement("afterend",d);}else{sec.appendChild(d);}}catch(e){}}
async function saveProfile(){try{await api("/profile/update","POST",{phone:document.getElementById("mPhone").value,bio:document.getElementById("mBio").value},true);alert("Profile saved!");}catch(e){alert(e.message);}}
async function loadStats(){var box=document.getElementById("statsBox");if(!box)return;try{var a=await api("/analytics","GET",null,true);var h="<h3 style='color:#7DD3FC'>Team Activity</h3>";a.agents.forEach(function(g){h+='<div class="item"><div class="item-info"><h3>'+g.name+'</h3><p>Leads: '+g.ad_lead+'</p></div></div>';});box.innerHTML=h;}catch(e){box.innerHTML='<p style="color:#EF4444">'+e.message+'</p>';}}
async function loadBot(){var box=document.getElementById("botStatus");if(!box)return;try{var s=await api("/ai-bot/status","GET",null,true);box.innerHTML='<p style="color:'+(s.enabled?"#22C55E":"#EF4444")+';font-weight:700">Bot is '+(s.enabled?"ON - replying 24/7":"OFF")+'</p>';}catch(e){box.innerHTML='<p style="color:#EF4444">'+e.message+'</p>';}}
async function toggleBot(){try{var s=await api("/ai-bot/toggle","POST",{},true);alert("Bot is now "+(s.enabled?"ON":"OFF"));loadBot();}catch(e){alert(e.message);}}
async function loadPublicShowroom(){var box=document.getElementById("publicCars");if(!box)return;try{var r=await fetch(API+"/products");var cars=await r.json();if(!cars||!cars.length){box.innerHTML='<p style="color:#94A3B8;grid-column:1/-1;text-align:center">Showroom opening soon!</p>';return;}var h="";cars.slice(0,8).forEach(function(c){var img="";if(c.images&&c.images.length>0){img=Array.isArray(c.images)?c.images[0]:c.images;}else if(c.image_url){img=c.image_url;}h+='<a href="'+location.origin+'/api/v1/dashboard/car/'+c.id+'" style="text-decoration:none"><div class="card" style="margin:0;padding:10px">'+(img?'<img src="'+img+'" loading="lazy" style="width:100%;height:110px;object-fit:cover;border-radius:10px">':'')+'<div style="font-size:13px;font-weight:700;margin-top:6px;color:#F8FAFC">'+c.name+'</div><div style="color:#10B981;font-weight:800;font-size:13px">&#8358;'+Number(c.price).toLocaleString()+'</div></div></a>';});box.innerHTML=h;}catch(e){box.innerHTML='<p style="color:#94A3B8;grid-column:1/-1;text-align:center">Welcome! Sign in to explore.</p>';}}
function generateStatusImage(idx){var car=(window.CARS||[])[idx];if(!car)return;toast("Generating watermark...");api("/profile/me","GET",null,true).then(function(p){drawCanvas(car,p.full_name||"Sodangi Motors",p.phone||"08000000000");}).catch(function(){drawCanvas(car,"Sodangi Motors","08000000000");});}
function drawCanvas(car,name,phone){var canvas=document.createElement("canvas");var ctx=canvas.getContext("2d");var img=new Image();img.crossOrigin="anonymous";var src="";if(car.images&&car.images.length>0){src=car.images[0];}if(!src){toast("No image found.");return;}img.onload=function(){canvas.width=1080;canvas.height=1920;var scale=Math.max(canvas.width/img.width,canvas.height/img.height);var x=(canvas.width-img.width*scale)/2;var y=(canvas.height-img.height*scale)/2;ctx.drawImage(img,x,y,img.width*scale,img.height*scale);var g=ctx.createLinearGradient(0,canvas.height-600,0,canvas.height);g.addColorStop(0,"rgba(0,0,0,0)");g.addColorStop(1,"rgba(0,0,0,0.95)");ctx.fillStyle=g;ctx.fillRect(0,canvas.height-600,canvas.width,600);ctx.textAlign="center";ctx.fillStyle="#fff";ctx.font="bold 70px sans-serif";ctx.fillText(car.name,canvas.width/2,canvas.height-350);ctx.fillStyle="#10B981";ctx.font="bold 100px sans-serif";ctx.fillText("\u20A6"+Number(car.price).toLocaleString(),canvas.width/2,canvas.height-220);ctx.fillStyle="#fff";ctx.font="bold 50px sans-serif";ctx.fillText(name,canvas.width/2,canvas.height-110);ctx.fillStyle="#FBBF24";ctx.font="bold 60px sans-serif";ctx.fillText(phone,canvas.width/2,canvas.height-40);try{var a=document.createElement("a");a.download=car.name.replace(/\s+/g,"_")+"_Status.png";a.href=canvas.toDataURL("image/png");a.click();toast("Status saved!");}catch(e){canvas.toBlob(function(b){window.open(URL.createObjectURL(b),"_blank");});}};img.onerror=function(){toast("Error loading image.");};img.src=src;}
document.addEventListener("click",function(ev){var t=ev.target;var el=t.closest?t.closest("[data-act]"):null;if(!el)return;var act=el.getAttribute("data-act");if(act==="delcar"){ev.preventDefault();delCar(parseInt(el.getAttribute("data-pid"),10));}});
if(TOKEN){enterDash();}else{loadPublicShowroom();initSocial();}
'''

anchor = '</script>\n</body>\n</html>"""'
if "/*ENGINE2*/" not in code and anchor in code:
    code = code.replace(anchor, '</script>\n<script>\n/*ENGINE2*/\n' + ENGINE + '\n' + anchor, 1)
    print("✅ ENGINE 2 injected - every button now has a living link!")
else:
    print("ℹ️ Engine 2 already present or anchor missing.")

ast.parse(code)
with open(fp, "w", encoding="utf-8") as f:
    f.write(code)
print("✅ Saved!")

print("Pushing to GitHub...")
subprocess.run(["git", "add", "."], check=False)
subprocess.run(["git", "commit", "-m", "Engine 2 Button Linker: independent JS engine guarantees all buttons work"], check=False)
for i in range(3):
    r = subprocess.run(["git", "push", "origin", "main", "--force"], capture_output=True, text=True)
    if r.returncode == 0:
        print("✅ Push successful!")
        break
    print("Push failed attempt " + str(i+1) + ", retrying...")
    time.sleep(5)
