"""final_schema_for_production



Revision ID: c10ac2e075e7

Revises: c8b6e17933e4

Create Date: 2026-08-24 03:52:24.022305



"""

from typing import Sequence, Union



from alembic import op

import sqlalchemy as sa

import app.models.whatsapp  # noqa: E402  (custom EncryptedString type)





# revision identifiers, used by Alembic.

revision: str = "c10ac2e075e7"

down_revision: Union[str, None] = "c8b6e17933e4"

branch_labels: Union[str, Sequence[str], None] = None

depends_on: Union[str, Sequence[str], None] = None





# --------------------------------------------------------------------------- #

# Idempotency helpers

# --------------------------------------------------------------------------- #

def _has_table(table_name: str) -> bool:

    """Return True if *table_name* already exists in the current bind."""

    from sqlalchemy import inspect as sa_inspect
    inspector = sa_inspect(op.get_bind())

    return table_name in inspector.get_table_names()





def _get_columns(table_name: str) -> set:

    if not _has_table(table_name):

        return set()

    from sqlalchemy import inspect as sa_inspect
    inspector = sa_inspect(op.get_bind())

    return {col["name"] for col in inspector.get_columns(table_name)}





def _get_indexes(table_name: str) -> set:

    if not _has_table(table_name):

        return set()

    from sqlalchemy import inspect as sa_inspect
    inspector = sa_inspect(op.get_bind())

    return {idx["name"] for idx in inspector.get_indexes(table_name)}





def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###

    # NOTE: This migration is idempotent. It was auto-generated from model

    # metadata while tables already existed in the database (created by

    # ``init_db.py``'s ``Base.metadata.create_all``).



    # --- sms_messages -------------------------------------------------------

    if not _has_table("sms_messages"):

        op.create_table(

            "sms_messages",

            sa.Column("id", sa.Integer(), nullable=False),

            sa.Column("business_id", sa.Integer(), nullable=False),

            sa.Column("to_phone", sa.String(length=50), nullable=False),

            sa.Column("body", sa.Text(), nullable=False),

            sa.Column("provider", sa.String(length=50), nullable=False),

            sa.Column("status", sa.String(length=30), nullable=False),

            sa.Column("provider_message_id", sa.String(length=255), nullable=False),

            sa.Column("error_message", sa.Text(), nullable=False),

            sa.Column("created_at", sa.DateTime(), nullable=False),

            sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),

            sa.PrimaryKeyConstraint("id"),

        )

    with op.batch_alter_table("sms_messages", schema=None) as batch_op:

        existing = _get_indexes("sms_messages")

        if "ix_sms_messages_business_id" not in existing:

            batch_op.create_index(batch_op.f("ix_sms_messages_business_id"), ["business_id"], unique=False)

        if "ix_sms_messages_created_at" not in existing:

            batch_op.create_index(batch_op.f("ix_sms_messages_created_at"), ["created_at"], unique=False)

        if "ix_sms_messages_status" not in existing:

            batch_op.create_index(batch_op.f("ix_sms_messages_status"), ["status"], unique=False)

        if "ix_sms_messages_to_phone" not in existing:

            batch_op.create_index(batch_op.f("ix_sms_messages_to_phone"), ["to_phone"], unique=False)



    # --- whatsapp_templates -------------------------------------------------

    if not _has_table("whatsapp_templates"):

        op.create_table(

            "whatsapp_templates",

            sa.Column("id", sa.Integer(), nullable=False),

            sa.Column("business_id", sa.Integer(), nullable=False),

            sa.Column("template_name", sa.String(length=255), nullable=False),

            sa.Column("template_text", sa.Text(), nullable=False),

            sa.Column("variables", sa.JSON(), nullable=False),

            sa.Column("category", sa.String(length=30), nullable=False),

            sa.Column("status", sa.String(length=20), nullable=False),

            sa.Column("created_at", sa.DateTime(), nullable=False),

            sa.Column("updated_at", sa.DateTime(), nullable=False),

            sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),

            sa.PrimaryKeyConstraint("id"),

        )

    with op.batch_alter_table("whatsapp_templates", schema=None) as batch_op:

        existing = _get_indexes("whatsapp_templates")

        if "ix_whatsapp_templates_business_id" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_templates_business_id"), ["business_id"], unique=False)

        if "ix_whatsapp_templates_business_name" not in existing:

            batch_op.create_index("ix_whatsapp_templates_business_name", ["business_id", "template_name"], unique=True)

        if "ix_whatsapp_templates_category" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_templates_category"), ["category"], unique=False)

        if "ix_whatsapp_templates_status" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_templates_status"), ["status"], unique=False)



    # --- orders -------------------------------------------------------------

    if not _has_table("orders"):

        op.create_table(

            "orders",

            sa.Column("id", sa.Integer(), nullable=False),

            sa.Column("reference", sa.String(), nullable=False),

            sa.Column("customer_id", sa.Integer(), nullable=True),

            sa.Column("total_amount", sa.Float(), nullable=False),

            sa.Column("status", sa.Enum("PENDING", "PAID", "CANCELLED", "FULFILLED", name="orderstatus"), nullable=True),

            sa.Column("delivery_address", sa.String(), nullable=True),

            sa.Column("paystack_checkout_url", sa.String(), nullable=True),

            sa.Column("metadata_json", sa.JSON(), nullable=True),

            sa.Column("created_at", sa.DateTime(), nullable=True),

            sa.ForeignKeyConstraint(["customer_id"], ["customers.id"]),

            sa.PrimaryKeyConstraint("id"),

        )

    with op.batch_alter_table("orders", schema=None) as batch_op:

        existing = _get_indexes("orders")

        if "ix_orders_id" not in existing:

            batch_op.create_index(batch_op.f("ix_orders_id"), ["id"], unique=False)

        if "ix_orders_reference" not in existing:

            batch_op.create_index(batch_op.f("ix_orders_reference"), ["reference"], unique=True)



    # --- whatsapp_campaigns -------------------------------------------------

    if not _has_table("whatsapp_campaigns"):

        op.create_table(

            "whatsapp_campaigns",

            sa.Column("id", sa.Integer(), nullable=False),

            sa.Column("business_id", sa.Integer(), nullable=False),

            sa.Column("account_id", sa.Integer(), nullable=False),

            sa.Column("campaign_name", sa.String(length=255), nullable=False),

            sa.Column("status", sa.String(length=20), nullable=False),

            sa.Column("template_id", sa.Integer(), nullable=True),

            sa.Column("scheduled_time", sa.DateTime(), nullable=True),

            sa.Column("started_at", sa.DateTime(), nullable=True),

            sa.Column("completed_at", sa.DateTime(), nullable=True),

            sa.Column("total_recipients", sa.Integer(), nullable=False),

            sa.Column("sent_count", sa.Integer(), nullable=False),

            sa.Column("delivered_count", sa.Integer(), nullable=False),

            sa.Column("read_count", sa.Integer(), nullable=False),

            sa.Column("failed_count", sa.Integer(), nullable=False),

            sa.Column("reply_count", sa.Integer(), nullable=False),

            sa.Column("error_log", sa.JSON(), nullable=False),

            sa.Column("created_at", sa.DateTime(), nullable=False),

            sa.Column("updated_at", sa.DateTime(), nullable=False),

            sa.ForeignKeyConstraint(["account_id"], ["whatsapp_accounts.id"], ondelete="CASCADE"),

            sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),

            sa.ForeignKeyConstraint(["template_id"], ["whatsapp_templates.id"], ondelete="SET NULL"),

            sa.PrimaryKeyConstraint("id"),

        )

    with op.batch_alter_table("whatsapp_campaigns", schema=None) as batch_op:

        existing = _get_indexes("whatsapp_campaigns")

        if "ix_whatsapp_campaigns_account_id" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_campaigns_account_id"), ["account_id"], unique=False)

        if "ix_whatsapp_campaigns_business_id" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_campaigns_business_id"), ["business_id"], unique=False)

        if "ix_whatsapp_campaigns_business_status" not in existing:

            batch_op.create_index("ix_whatsapp_campaigns_business_status", ["business_id", "status"], unique=False)

        if "ix_whatsapp_campaigns_scheduled_time" not in existing:

            batch_op.create_index("ix_whatsapp_campaigns_scheduled_time", ["scheduled_time"], unique=False)

        if "ix_whatsapp_campaigns_status" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_campaigns_status"), ["status"], unique=False)



    # --- order_items --------------------------------------------------------

    if not _has_table("order_items"):

        op.create_table(

            "order_items",

            sa.Column("id", sa.Integer(), nullable=False),

            sa.Column("order_id", sa.Integer(), nullable=False),

            sa.Column("product_id", sa.Integer(), nullable=False),

            sa.Column("quantity", sa.Integer(), nullable=False),

            sa.Column("unit_price", sa.Float(), nullable=False),

            sa.ForeignKeyConstraint(["order_id"], ["orders.id"]),

            sa.ForeignKeyConstraint(["product_id"], ["products.id"]),

            sa.PrimaryKeyConstraint("id"),

        )

    with op.batch_alter_table("order_items", schema=None) as batch_op:

        existing = _get_indexes("order_items")

        if "ix_order_items_id" not in existing:

            batch_op.create_index(batch_op.f("ix_order_items_id"), ["id"], unique=False)



    # --- whatsapp_recipients ------------------------------------------------

    if not _has_table("whatsapp_recipients"):

        op.create_table(

            "whatsapp_recipients",

            sa.Column("id", sa.Integer(), nullable=False),

            sa.Column("campaign_id", sa.Integer(), nullable=False),

            sa.Column("customer_id", sa.Integer(), nullable=True),

            sa.Column("phone_number", sa.String(length=50), nullable=False),

            sa.Column("status", sa.String(length=20), nullable=False),

            sa.Column("delivery_timestamp", sa.DateTime(), nullable=True),

            sa.Column("read_timestamp", sa.DateTime(), nullable=True),

            sa.Column("replied", sa.Boolean(), nullable=False),

            sa.Column("reply_text", sa.Text(), nullable=False),

            sa.Column("error_message", sa.Text(), nullable=False),

            sa.Column("created_at", sa.DateTime(), nullable=False),

            sa.Column("updated_at", sa.DateTime(), nullable=False),

            sa.ForeignKeyConstraint(["campaign_id"], ["whatsapp_campaigns.id"], ondelete="CASCADE"),

            sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="SET NULL"),

            sa.PrimaryKeyConstraint("id"),

        )

    with op.batch_alter_table("whatsapp_recipients", schema=None) as batch_op:

        existing = _get_indexes("whatsapp_recipients")

        if "ix_whatsapp_recipients_campaign_id" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_recipients_campaign_id"), ["campaign_id"], unique=False)

        if "ix_whatsapp_recipients_campaign_status" not in existing:

            batch_op.create_index("ix_whatsapp_recipients_campaign_status", ["campaign_id", "status"], unique=False)

        if "ix_whatsapp_recipients_customer_id" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_recipients_customer_id"), ["customer_id"], unique=False)

        if "ix_whatsapp_recipients_status" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_recipients_status"), ["status"], unique=False)



    # --- whatsapp_messages --------------------------------------------------

    if not _has_table("whatsapp_messages"):

        op.create_table(

            "whatsapp_messages",

            sa.Column("id", sa.Integer(), nullable=False),

            sa.Column("business_id", sa.Integer(), nullable=False),

            sa.Column("account_id", sa.Integer(), nullable=False),

            sa.Column("to_number", sa.String(length=50), nullable=False),

            sa.Column("from_number", sa.String(length=50), nullable=False),

            sa.Column("message_text", sa.Text(), nullable=False),

            sa.Column("status", sa.String(length=30), nullable=False),

            sa.Column("delivery_timestamp", sa.DateTime(), nullable=True),

            sa.Column("read_timestamp", sa.DateTime(), nullable=True),

            sa.Column("message_type", sa.String(length=30), nullable=False),

            sa.Column("media_url", sa.String(length=500), nullable=False),

            sa.Column("media_id", sa.String(length=255), nullable=False),

            sa.Column("transcript", sa.Text(), nullable=False),

            sa.Column("direction", sa.String(length=10), nullable=False),

            sa.Column("is_reply", sa.Boolean(), nullable=False),

            sa.Column("reply_text", sa.Text(), nullable=False),

            sa.Column("error_message", sa.Text(), nullable=False),

            sa.Column("campaign_id", sa.Integer(), nullable=True),

            sa.Column("recipient_id", sa.Integer(), nullable=True),

            sa.Column("created_at", sa.DateTime(), nullable=False),

            sa.Column("updated_at", sa.DateTime(), nullable=False),

            sa.ForeignKeyConstraint(["account_id"], ["whatsapp_accounts.id"], ondelete="CASCADE"),

            sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),

            sa.ForeignKeyConstraint(["campaign_id"], ["whatsapp_campaigns.id"], ondelete="SET NULL"),

            sa.ForeignKeyConstraint(["recipient_id"], ["whatsapp_recipients.id"], ondelete="SET NULL"),

            sa.PrimaryKeyConstraint("id"),

        )

    with op.batch_alter_table("whatsapp_messages", schema=None) as batch_op:

        existing = _get_indexes("whatsapp_messages")

        if "ix_whatsapp_messages_account_id" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_messages_account_id"), ["account_id"], unique=False)

        if "ix_whatsapp_messages_business_created" not in existing:

            batch_op.create_index("ix_whatsapp_messages_business_created", ["business_id", "created_at"], unique=False)

        if "ix_whatsapp_messages_business_id" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_messages_business_id"), ["business_id"], unique=False)

        if "ix_whatsapp_messages_campaign_id" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_messages_campaign_id"), ["campaign_id"], unique=False)

        if "ix_whatsapp_messages_created_at" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_messages_created_at"), ["created_at"], unique=False)

        if "ix_whatsapp_messages_direction" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_messages_direction"), ["direction"], unique=False)

        if "ix_whatsapp_messages_recipient_id" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_messages_recipient_id"), ["recipient_id"], unique=False)

        if "ix_whatsapp_messages_status" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_messages_status"), ["status"], unique=False)



    # --- whatsapp_engagements -----------------------------------------------

    if not _has_table("whatsapp_engagements"):

        op.create_table(

            "whatsapp_engagements",

            sa.Column("id", sa.Integer(), nullable=False),

            sa.Column("business_id", sa.Integer(), nullable=False),

            sa.Column("message_id", sa.Integer(), nullable=False),

            sa.Column("campaign_id", sa.Integer(), nullable=True),

            sa.Column("customer_id", sa.Integer(), nullable=True),

            sa.Column("event_type", sa.String(length=20), nullable=False),

            sa.Column("event_timestamp", sa.DateTime(), nullable=False),

            sa.Column("response_time_seconds", sa.Integer(), nullable=True),

            sa.Column("created_at", sa.DateTime(), nullable=False),

            sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),

            sa.ForeignKeyConstraint(["campaign_id"], ["whatsapp_campaigns.id"], ondelete="SET NULL"),

            sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="SET NULL"),

            sa.ForeignKeyConstraint(["message_id"], ["whatsapp_messages.id"], ondelete="CASCADE"),

            sa.PrimaryKeyConstraint("id"),

        )

    with op.batch_alter_table("whatsapp_engagements", schema=None) as batch_op:

        existing = _get_indexes("whatsapp_engagements")

        if "ix_whatsapp_engagements_business_event" not in existing:

            batch_op.create_index("ix_whatsapp_engagements_business_event", ["business_id", "event_type"], unique=False)

        if "ix_whatsapp_engagements_business_id" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_engagements_business_id"), ["business_id"], unique=False)

        if "ix_whatsapp_engagements_campaign_id" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_engagements_campaign_id"), ["campaign_id"], unique=False)

        if "ix_whatsapp_engagements_customer_id" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_engagements_customer_id"), ["customer_id"], unique=False)

        if "ix_whatsapp_engagements_event_timestamp" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_engagements_event_timestamp"), ["event_timestamp"], unique=False)

        if "ix_whatsapp_engagements_event_ts" not in existing:

            batch_op.create_index("ix_whatsapp_engagements_event_ts", ["event_timestamp"], unique=False)

        if "ix_whatsapp_engagements_event_type" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_engagements_event_type"), ["event_type"], unique=False)

        if "ix_whatsapp_engagements_message_id" not in existing:

            batch_op.create_index(batch_op.f("ix_whatsapp_engagements_message_id"), ["message_id"], unique=False)

    # --- whatsapp_accounts (add missing columns & indexes) ------------------

    wa_columns = _get_columns("whatsapp_accounts")

    wa_indexes = _get_indexes("whatsapp_accounts")

    with op.batch_alter_table("whatsapp_accounts", schema=None) as batch_op:

        if "api_key" not in wa_columns:

            batch_op.add_column(sa.Column("api_key", app.models.whatsapp.EncryptedString(length=500), nullable=False))

        if "account_name" not in wa_columns:

            batch_op.add_column(sa.Column("account_name", sa.String(length=255), nullable=False))

        if "status" not in wa_columns:

            batch_op.add_column(sa.Column("status", sa.String(length=20), nullable=False))

        if "rate_limit_per_hour" not in wa_columns:

            batch_op.add_column(sa.Column("rate_limit_per_hour", sa.Integer(), nullable=False))

        if "ix_whatsapp_accounts_business_phone" not in wa_indexes:

            batch_op.create_index("ix_whatsapp_accounts_business_phone", ["business_id", "phone_number"], unique=True)

        if "ix_whatsapp_accounts_status" not in wa_indexes:

            batch_op.create_index(batch_op.f("ix_whatsapp_accounts_status"), ["status"], unique=False)



    # ### end Alembic commands ###





def downgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###

    # NOTE: idempotent downgrade - only drops objects that still exist.



    wa_columns = _get_columns("whatsapp_accounts")

    wa_indexes = _get_indexes("whatsapp_accounts")

    with op.batch_alter_table("whatsapp_accounts", schema=None) as batch_op:

        if "ix_whatsapp_accounts_status" in wa_indexes:

            batch_op.drop_index(batch_op.f("ix_whatsapp_accounts_status"))

        if "ix_whatsapp_accounts_business_phone" in wa_indexes:

            batch_op.drop_index("ix_whatsapp_accounts_business_phone")

        if "rate_limit_per_hour" in wa_columns:

            batch_op.drop_column("rate_limit_per_hour")

        if "status" in wa_columns:

            batch_op.drop_column("status")

        if "account_name" in wa_columns:

            batch_op.drop_column("account_name")

        if "api_key" in wa_columns:

            batch_op.drop_column("api_key")



    # --- whatsapp_engagements (drop if exists) -------------------------------

    if _has_table("whatsapp_engagements"):

        existing = _get_indexes("whatsapp_engagements")

        with op.batch_alter_table("whatsapp_engagements", schema=None) as batch_op:

            if "ix_whatsapp_engagements_message_id" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_engagements_message_id"))

            if "ix_whatsapp_engagements_event_type" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_engagements_event_type"))

            if "ix_whatsapp_engagements_event_ts" in existing:

                batch_op.drop_index("ix_whatsapp_engagements_event_ts")

            if "ix_whatsapp_engagements_event_timestamp" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_engagements_event_timestamp"))

            if "ix_whatsapp_engagements_customer_id" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_engagements_customer_id"))

            if "ix_whatsapp_engagements_campaign_id" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_engagements_campaign_id"))

            if "ix_whatsapp_engagements_business_id" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_engagements_business_id"))

            if "ix_whatsapp_engagements_business_event" in existing:

                batch_op.drop_index("ix_whatsapp_engagements_business_event")

        op.drop_table("whatsapp_engagements")



    # --- whatsapp_messages (drop if exists) ----------------------------------

    if _has_table("whatsapp_messages"):

        existing = _get_indexes("whatsapp_messages")

        with op.batch_alter_table("whatsapp_messages", schema=None) as batch_op:

            if "ix_whatsapp_messages_status" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_messages_status"))

            if "ix_whatsapp_messages_recipient_id" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_messages_recipient_id"))

            if "ix_whatsapp_messages_direction" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_messages_direction"))

            if "ix_whatsapp_messages_created_at" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_messages_created_at"))

            if "ix_whatsapp_messages_campaign_id" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_messages_campaign_id"))

            if "ix_whatsapp_messages_business_id" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_messages_business_id"))

            if "ix_whatsapp_messages_business_created" in existing:

                batch_op.drop_index("ix_whatsapp_messages_business_created")

            if "ix_whatsapp_messages_account_id" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_messages_account_id"))

        op.drop_table("whatsapp_messages")

    # --- whatsapp_recipients (drop if exists) --------------------------------

    if _has_table("whatsapp_recipients"):

        existing = _get_indexes("whatsapp_recipients")

        with op.batch_alter_table("whatsapp_recipients", schema=None) as batch_op:

            if "ix_whatsapp_recipients_status" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_recipients_status"))

            if "ix_whatsapp_recipients_customer_id" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_recipients_customer_id"))

            if "ix_whatsapp_recipients_campaign_status" in existing:

                batch_op.drop_index("ix_whatsapp_recipients_campaign_status")

            if "ix_whatsapp_recipients_campaign_id" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_recipients_campaign_id"))

        op.drop_table("whatsapp_recipients")



    # --- order_items (drop if exists) ----------------------------------------

    if _has_table("order_items"):

        existing = _get_indexes("order_items")

        with op.batch_alter_table("order_items", schema=None) as batch_op:

            if "ix_order_items_id" in existing:

                batch_op.drop_index(batch_op.f("ix_order_items_id"))

        op.drop_table("order_items")



    # --- whatsapp_campaigns (drop if exists) ---------------------------------

    if _has_table("whatsapp_campaigns"):

        existing = _get_indexes("whatsapp_campaigns")

        with op.batch_alter_table("whatsapp_campaigns", schema=None) as batch_op:

            if "ix_whatsapp_campaigns_status" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_campaigns_status"))

            if "ix_whatsapp_campaigns_scheduled_time" in existing:

                batch_op.drop_index("ix_whatsapp_campaigns_scheduled_time")

            if "ix_whatsapp_campaigns_business_status" in existing:

                batch_op.drop_index("ix_whatsapp_campaigns_business_status")

            if "ix_whatsapp_campaigns_business_id" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_campaigns_business_id"))

            if "ix_whatsapp_campaigns_account_id" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_campaigns_account_id"))

        op.drop_table("whatsapp_campaigns")



    # --- orders (drop if exists) ---------------------------------------------

    if _has_table("orders"):

        existing = _get_indexes("orders")

        with op.batch_alter_table("orders", schema=None) as batch_op:

            if "ix_orders_reference" in existing:

                batch_op.drop_index(batch_op.f("ix_orders_reference"))

            if "ix_orders_id" in existing:

                batch_op.drop_index(batch_op.f("ix_orders_id"))

        op.drop_table("orders")



    # --- whatsapp_templates (drop if exists) ---------------------------------

    if _has_table("whatsapp_templates"):

        existing = _get_indexes("whatsapp_templates")

        with op.batch_alter_table("whatsapp_templates", schema=None) as batch_op:

            if "ix_whatsapp_templates_status" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_templates_status"))

            if "ix_whatsapp_templates_category" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_templates_category"))

            if "ix_whatsapp_templates_business_name" in existing:

                batch_op.drop_index("ix_whatsapp_templates_business_name")

            if "ix_whatsapp_templates_business_id" in existing:

                batch_op.drop_index(batch_op.f("ix_whatsapp_templates_business_id"))

        op.drop_table("whatsapp_templates")



    # --- sms_messages (drop if exists) ---------------------------------------

    if _has_table("sms_messages"):

        existing = _get_indexes("sms_messages")

        with op.batch_alter_table("sms_messages", schema=None) as batch_op:

            if "ix_sms_messages_to_phone" in existing:

                batch_op.drop_index(batch_op.f("ix_sms_messages_to_phone"))

            if "ix_sms_messages_status" in existing:

                batch_op.drop_index(batch_op.f("ix_sms_messages_status"))

            if "ix_sms_messages_created_at" in existing:

                batch_op.drop_index(batch_op.f("ix_sms_messages_created_at"))

            if "ix_sms_messages_business_id" in existing:

                batch_op.drop_index(batch_op.f("ix_sms_messages_business_id"))

        op.drop_table("sms_messages")

    # ### end Alembic commands ###

